version: "3.7"

services:
  bind9:
    build: ../../build/package/bind9/
    hostname: bind9
    domainname: oink
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.2

  kazoo-rabbitmq:
    depends_on:
      - bind9
    build: ../../build/package/rabbitmq/
    hostname: kazoo-rabbitmq
    domainname: oink
    dns:
      - 172.16.0.2
    dns_search:
      - oink
    ports:
      - "15672:15672"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.10

  kazoo-couchdb:
    depends_on:
      - bind9
    build: ../../build/package/couchdb/
    hostname: kazoo-couchdb
    domainname: oink
    dns:
      - 172.16.0.2
    dns_search:
      - oink
    ports:
      - "5984:5984"
      - "5986:5986"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.20

  kazoo-kamailio:
    depends_on:
      - bind9
      - kazoo-rabbitmq
    build: ../../build/package/kamailio/
    hostname: kazoo-kamailio
    domainname: oink
    dns:
      - 172.16.0.2
    dns_search:
      - oink
    ports:
      - "5060:5060/udp"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.30

  kazoo-freeswitch:
    depends_on:
      - bind9
    build: ../../build/package/freeswitch/
    hostname: kazoo-freeswitch
    domainname: oink
    dns:
      - 172.16.0.2
    dns_search:
      - oink
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.40

  kazoo-apps:
    depends_on:
      - bind9
      - kazoo-couchdb
      - kazoo-rabbitmq
      - kazoo-freeswitch
      - kazoo-kamailio
    build: ../../build/package/kazoo/
    command: /home/kazoo/src/kazoo/scripts/dev/kazoo.sh foreground
    hostname: kazoo-apps
    domainname: oink
    dns:
      - 172.16.0.2
    dns_search:
      - oink
    environment:
      - KAZOO_APPS=blackhole,callflow,cdr,conference,crossbar,ecallmgr,fax,hangups,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,tasks,teletype,trunkstore,webhooks
    ports:
      - "8000:8000"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.50

  kazoo-ui:
    depends_on:
      - bind9
      - kazoo-apps
    build: ../../build/package/monster-ui/
    hostname: kazoo-ui
    domainname: oink
    dns:
      - 172.16.0.2
    dns_search:
      - oink
    ports:
      - "80:3000"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.60

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
