version: "3.7"

services:
  kazoo-rabbitmq:
    build: ../../build/package/rabbitmq/
    hostname: kazoo-rabbitmq
    domainname: oink_app_net
    ports:
      - "15672:15672"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.10

  kazoo-couchdb:
    build: ../../build/package/couchdb/
    hostname: kazoo-couchdb
    domainname: oink_app_net
    ports:
      - "5984:5984"
      - "5986:5986"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.20

  kazoo-kamailio:
    depends_on:
      - kazoo-rabbitmq
    build: ../../build/package/kamailio/
    hostname: kazoo-kamailio
    domainname: oink_app_net
    dns:
      - 172.16.0.2
    dns_search:
      - oink
    ports:
      - "5060:5060/udp"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.30

  kazoo-freeswitch-alpha:
    depends_on:
      - kazoo-postgres
    build: $FREESWITCH_SOURCE
    hostname: kazoo-freeswitch-alpha
    domainname: oink_app_net
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.41
  kazoo-freeswitch-beta:
    depends_on:
      - kazoo-postgres
    build: $FREESWITCH_SOURCE
    hostname: kazoo-freeswitch-beta
    domainname: oink_app_net
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.42

  kazoo-apps:
    depends_on:
      - kazoo-couchdb
      - kazoo-rabbitmq
      - kazoo-freeswitch-alpha
      - kazoo-freeswitch-beta
      - kazoo-kamailio
    build: ../../build/package/kazoo/
    command: bash -c "make -C src/kazoo &&
      make -C src/kazoo build-dev-release &&
      src/kazoo/_rel/kazoo/bin/kazoo foreground"
    hostname: kazoo-apps
    domainname: oink_app_net
    environment:
      - KAZOO_APPS=blackhole,callflow,cdr,conference,crossbar,ecallmgr,fax,hangups,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,tasks,teletype,trunkstore,webhooks
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: $KAZOO_SOURCE
        target: /home/kazoo/src/kazoo
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.50

  kazoo-ui:
    depends_on:
      - kazoo-apps
    build: ../../build/package/monster-ui/
    hostname: kazoo-ui
    domainname: oink_app_net
    ports:
      - "80:3000"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.60

  kazoo-postgres:
    image: postgres
    hostname: kazoo-postgres
    domainname: oink_app_net
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_NICE
      - SYS_PTRACE
    networks:
      app_net:
        ipv4_address: 172.16.0.70

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
